version: '3.7'

services:
  app-server:
    container_name: backend
    build:
      context: .
      dockerfile: DockerfileTest
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    networks:
      - backend
  db:
    container_name: mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: wololotacs
      MYSQL_USER: wololotacs
      MYSQL_PASSWORD: wololotacs
      MYSQL_ROOT_PASSWORD: root
    networks:
      - backend

  front:
    container_name: frontend
    command: "npm start"
    build:
      context: src/main/ui
      dockerfile: Dockerfile
    ports:
    - "4200:4200"
    depends_on:
    - db
    restart: always
    networks:
    - backend

networks:
  backend:
