version: '3.7'

services:
  app-server:
    container_name: backend
    build:
      context: .
      dockerfile: DockerfileTest
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    networks:
      - backend

  db:
    container_name: mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: polls
      MYSQL_USER: callicoder
      MYSQL_PASSWORD: callicoder
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

volumes:
 db-data:

networks:
  backend: